### ISSUE TITLE
Provide login help on Dashboard

### ISSUE THREAD

**Issue by jvanulde** [OpenDRR/opendrr-api#101]
Can we enable the "Need help?" functionality explaining to users that they have to send us an email to have an account created? Via `xpack.security.loginHelp` perhaps?

**Comment by arashmalekz** [comment]
@jvanulde Is there any specific text you'd like to display? We can use markdown for formatting the text. This is how it would look like: 
![image](https://user-images.githubusercontent.com/54640785/120226099-84517f00-c214-11eb-83c7-640ad1e54b01.png)

**Comment by jvanulde** [comment]
Maybe something like:

To create your own dashboards and visualizations you will need to have an account. Please contact joost.vanulden@canada.ca to have an account created for you.

Pour créer vos propres tableaux de bord et visualisations, vous devez disposer d'un compte. Veuillez contacter joost.vanulden@canada.ca pour qu'un compte soit créé pour vous.

**Comment by arashmalekz** [comment]
This is complete now and deployed to staging. Please review and let me know if there are any changes needed. Thanks.

**Comment by jvanulde** [comment]
I think that's okay but ideally, we would have that text on the first screen or on the screen where you are logging in with an account. I am not sure people will know to click the "Need help?".

**Comment by arashmalekz** [comment]
There's currently no easy way to customize the login page. Setting the content of "Need help?" section was easy because they allow customizing that. 
The only way to do what you mentioned is to modify the CSS/JS files inside the Kibana container itself and try to get a text  rendered properly on that page (This would be very time consuming). A less time consuming option could be looking into modifying the "Need help?" text itself inside Kibana container. Something like "Need an account?". And after you click on it then it will show you the page with the full text.

**Comment by jvanulde** [comment]
If we could do "Need an account?" that would be sufficient.

**Comment by arashmalekz** [comment]
Even changing that text wasn't easy, but I figured it out! It's deployed to staging now.

**Comment by arashmalekz** [comment]
Forgot to mention, you may have to clear your cache so it pulls the new javascript files.

**Comment by jvanulde** [comment]
This will be sufficient for now. Thanks @arashmalekz
